name: Cypress Tests

on: [pull_request, pull_request_target, push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
     
     
      # - uses: suisei-cn/actions-download-file@v1
      #   id: pluginsindex  # Remember to give an ID if you need the output filename
      #   name: Plugins Index
      #   with:
      #     url: "https://desafio-cubos.s3.us-west-002.backblazeb2.com/cypress/plugins/index.js"
      #     target: cypress/plugins/
      # # =========================================================================
      # - uses: suisei-cn/actions-download-file@v1
      #   id: supportindex  # Remember to give an ID if you need the output filename
      #   name: Support Index
      #   with:
      #     url: "https://desafio-cubos.s3.us-west-002.backblazeb2.com/cypress/support/index.js"
      #     target: cypress/support/
      # # =========================================================================
      # - uses: suisei-cn/actions-download-file@v1
      #   id: commands  # Remember to give an ID if you need the output filename
      #   name: Commands
      #   with:
      #     url: "https://desafio-cubos.s3.us-west-002.backblazeb2.com/cypress/support/commands.js"
      #     target: cypress/support/
      # # =========================================================================
      # - uses: suisei-cn/actions-download-file@v1
      #   id: DefaultTransactions  # Remember to give an ID if you need the output filename
      #   name: Default Transaction
      #   with:
      #     url: "https://desafio-cubos.s3.us-west-002.backblazeb2.com/cypress/fixtures/transactions.json"
      #     target: cypress/fixtures/
     
      # # =========================================================================
      # - uses: suisei-cn/actions-download-file@v1
      #   id: DashboardSpec  # Remember to give an ID if you need the output filename
      #   name: Dashboard Spec 
      #   with:
      #     url: "https://desafio-cubos.s3.us-west-002.backblazeb2.com/cypress/integration/dashboard.spec.js"
      #     target: cypress/integration/     
      # # =========================================================================
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start